### ISSUE TITLE
Make a planet

### ISSUE THREAD

**Issue by nemobis** [paulirish/frontend-feeds#2]
Why not offer the feeds as a planet/aggregator too?
http://www.intertwingly.net/code/venus/docs/config.html says "At the moment, three formats of reading lists are supported: opml, foaf, csv, and config". On the other hand, not all feed readers know about OPML (mine does, but a friend of mine can't use it).

**Comment by paulirish** [comment]
Go for it!

**Comment by paulirish** [comment]
if someone wants to make this, i think it'd be great. maybe feedly etc can do it on our behalf?

(bloglines used to do this. <3 <3 )
